# Generated by Django 6.0.5 on 2026-05-08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BarcodeRegistry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("barcode", models.CharField(max_length=64, unique=True, verbose_name="barcode")),
                ("prefix", models.CharField(choices=[("ITM", "item"), ("WH", "warehouse"), ("RCK", "rack"), ("LOC", "location")], max_length=3, verbose_name="prefix")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
            ],
            options={
                "verbose_name": "barcode registry entry",
                "verbose_name_plural": "barcode registry entries",
                "ordering": ["barcode"],
            },
        ),
        migrations.CreateModel(
            name="BarcodeSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("prefix", models.CharField(choices=[("ITM", "item"), ("WH", "warehouse"), ("RCK", "rack"), ("LOC", "location")], max_length=3, unique=True, verbose_name="prefix")),
                ("next_number", models.PositiveBigIntegerField(default=1, verbose_name="next number")),
                ("padding", models.PositiveSmallIntegerField(default=8, verbose_name="padding")),
            ],
            options={
                "verbose_name": "barcode sequence",
                "verbose_name_plural": "barcode sequences",
                "ordering": ["prefix"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="core.category", verbose_name="parent category")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="name")),
                ("contact_name", models.CharField(blank=True, max_length=150, verbose_name="contact name")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "recipient",
                "verbose_name_plural": "recipients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("symbol", models.CharField(max_length=20, unique=True, verbose_name="symbol")),
            ],
            options={
                "verbose_name": "unit",
                "verbose_name_plural": "units",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="name")),
                ("address", models.TextField(blank=True, verbose_name="address")),
                ("barcode", models.OneToOneField(blank=True, limit_choices_to={"prefix": "WH"}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="warehouse", to="core.barcoderegistry", verbose_name="barcode")),
            ],
            options={
                "verbose_name": "warehouse",
                "verbose_name_plural": "warehouses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("internal_code", models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name="internal code")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("barcode", models.OneToOneField(blank=True, limit_choices_to={"prefix": "ITM"}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="item", to="core.barcoderegistry", verbose_name="barcode")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="items", to="core.category", verbose_name="category")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="core.unit", verbose_name="unit")),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("location_type", models.CharField(choices=[("location", "location"), ("rack", "rack")], default="location", max_length=20, verbose_name="location type")),
                ("barcode", models.OneToOneField(blank=True, limit_choices_to={"prefix__in": ["LOC", "RCK"]}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="location", to="core.barcoderegistry", verbose_name="barcode")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="locations", to="core.warehouse", verbose_name="warehouse")),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
                "ordering": ["warehouse__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("qty", models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name="quantity")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="core.item", verbose_name="item")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="core.location", verbose_name="location")),
            ],
            options={
                "verbose_name": "stock balance",
                "verbose_name_plural": "stock balances",
                "ordering": ["item__name", "location__name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("movement_type", models.CharField(choices=[("initial_balance", "initial balance"), ("in", "in"), ("out", "out"), ("return", "return"), ("writeoff", "write-off"), ("transfer", "transfer"), ("adjustment", "adjustment")], max_length=20, verbose_name="movement type")),
                ("qty", models.DecimalField(decimal_places=3, max_digits=18, verbose_name="quantity")),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="occurred at")),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                ("destination_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="incoming_stock_movements", to="core.location", verbose_name="destination location")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="core.item", verbose_name="item")),
                ("recipient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="core.recipient", verbose_name="recipient")),
                ("source_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="outgoing_stock_movements", to="core.location", verbose_name="source location")),
            ],
            options={
                "verbose_name": "stock movement",
                "verbose_name_plural": "stock movements",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("parent", "name"), name="core_category_unique_parent_name"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("warehouse", "name"), name="core_location_unique_warehouse_name"),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(fields=("item", "location"), name="core_stock_balance_unique_item_location"),
        ),
    ]
