# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_unique_parent_name",
        ),
        migrations.RemoveConstraint(
            model_name="location",
            name="core_location_unique_warehouse_name",
        ),
        migrations.AlterField(
            model_name="item",
            name="internal_code",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="internal code"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="symbol",
            field=models.CharField(max_length=20, verbose_name="symbol"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="name",
            field=models.CharField(max_length=150, verbose_name="name"),
        ),
    ]
