# Generated by Django 6.0.5 on 2026-05-08 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_soft_unique_validation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "width_mm",
                    models.PositiveSmallIntegerField(
                        default=58, verbose_name="width, mm"
                    ),
                ),
                (
                    "height_mm",
                    models.PositiveSmallIntegerField(
                        default=40, verbose_name="height, mm"
                    ),
                ),
                (
                    "show_item_name",
                    models.BooleanField(default=True, verbose_name="show item name"),
                ),
                (
                    "show_internal_code",
                    models.BooleanField(
                        default=True, verbose_name="show internal code"
                    ),
                ),
                (
                    "show_barcode_text",
                    models.BooleanField(default=True, verbose_name="show barcode text"),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[("code128", "Code 128")],
                        default="code128",
                        max_length=32,
                        verbose_name="barcode type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="default"),
                ),
            ],
            options={
                "verbose_name": "label template",
                "verbose_name_plural": "label templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "system_name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="system name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="default"),
                ),
            ],
            options={
                "verbose_name": "printer",
                "verbose_name_plural": "printers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=64, verbose_name="barcode")),
                (
                    "copies",
                    models.PositiveSmallIntegerField(default=1, verbose_name="copies"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("printed", "printed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="printed at"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_jobs",
                        to="core.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "label_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_jobs",
                        to="core.labeltemplate",
                        verbose_name="label template",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_jobs",
                        to="core.printer",
                        verbose_name="printer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "print job",
                "verbose_name_plural": "print jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
