# Generated by Django 6.0.5 on 2026-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_labeltemplate_printer_printjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcodesequence",
            name="padding",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="padding"),
        ),
    ]
