# Generated by Django 6.0.5 on 2026-05-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_barcodesequence_padding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="barcoderegistry",
            options={
                "ordering": ["barcode"],
                "verbose_name": "Реєстр штрихкодів",
                "verbose_name_plural": "Реєстр штрихкодів",
            },
        ),
        migrations.AlterModelOptions(
            name="barcodesequence",
            options={
                "ordering": ["prefix"],
                "verbose_name": "Послідовність штрихкодів",
                "verbose_name_plural": "Послідовності штрихкодів",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["name"],
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатура",
            },
        ),
        migrations.AlterModelOptions(
            name="labeltemplate",
            options={
                "ordering": ["name"],
                "verbose_name": "Шаблон етикеток",
                "verbose_name_plural": "Шаблони етикеток",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["warehouse__name", "name"],
                "verbose_name": "Локація",
                "verbose_name_plural": "Локації",
            },
        ),
        migrations.AlterModelOptions(
            name="printer",
            options={
                "ordering": ["name"],
                "verbose_name": "Принтер",
                "verbose_name_plural": "Принтери",
            },
        ),
        migrations.AlterModelOptions(
            name="printjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Завдання друку",
                "verbose_name_plural": "Завдання друку",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["name"],
                "verbose_name": "Отримувач",
                "verbose_name_plural": "Отримувачі",
            },
        ),
        migrations.AlterModelOptions(
            name="stockbalance",
            options={
                "ordering": ["item__name", "location__name"],
                "verbose_name": "Залишок",
                "verbose_name_plural": "Залишки",
            },
        ),
        migrations.AlterModelOptions(
            name="stockmovement",
            options={
                "ordering": ["-occurred_at", "-id"],
                "verbose_name": "Рух товарів",
                "verbose_name_plural": "Рухи товарів",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={
                "ordering": ["name"],
                "verbose_name": "Одиниця виміру",
                "verbose_name_plural": "Одиниці виміру",
            },
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "ordering": ["name"],
                "verbose_name": "Склад",
                "verbose_name_plural": "Склади",
            },
        ),
        migrations.AlterField(
            model_name="barcoderegistry",
            name="prefix",
            field=models.CharField(
                choices=[
                    ("ITM", "Номенклатура"),
                    ("WH", "Склад"),
                    ("RCK", "rack"),
                    ("LOC", "Локація"),
                ],
                max_length=3,
                verbose_name="prefix",
            ),
        ),
        migrations.AlterField(
            model_name="barcodesequence",
            name="prefix",
            field=models.CharField(
                choices=[
                    ("ITM", "Номенклатура"),
                    ("WH", "Склад"),
                    ("RCK", "rack"),
                    ("LOC", "Локація"),
                ],
                max_length=3,
                unique=True,
                verbose_name="prefix",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="core.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="core.unit",
                verbose_name="Одиниця виміру",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[("location", "Локація"), ("rack", "rack")],
                default="location",
                max_length=20,
                verbose_name="location type",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="core.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="print_jobs",
                to="core.item",
                verbose_name="Номенклатура",
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="label_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="print_jobs",
                to="core.labeltemplate",
                verbose_name="Шаблон етикеток",
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="printer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="print_jobs",
                to="core.printer",
                verbose_name="Принтер",
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_balances",
                to="core.item",
                verbose_name="Номенклатура",
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_balances",
                to="core.location",
                verbose_name="Локація",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="core.item",
                verbose_name="Номенклатура",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="core.recipient",
                verbose_name="Отримувач",
            ),
        ),
    ]
