# Generated by Django 6.0.5 on 2026-05-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_barcoderegistry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="department",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Цех / підрозділ"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="document_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Номер документа"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="issue_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale", "Продаж"),
                    ("repair", "Ремонтні роботи"),
                    ("production", "Виробничі потреби"),
                    ("other", "Інше"),
                ],
                max_length=20,
                verbose_name="Тип видачі",
            ),
        ),
    ]
