# Generated by Django 6.0.5 on 2026-05-09 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_inventorycount_inventorycountline"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="inventory_count",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="core.inventorycount",
                verbose_name="Inventory count",
            ),
        ),
    ]
