# Generated by Django 6.0.5 on 2026-05-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_systemsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsagePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="name"),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
            ],
            options={
                "verbose_name": "Цех / місце використання",
                "verbose_name_plural": "Цехи / місця використання",
                "ordering": ["name"],
            },
        ),
    ]
