# Generated by Django 6.0.5 on 2026-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_seed_usage_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeltemplate",
            name="barcode_bar_width_mm",
            field=models.DecimalField(
                decimal_places=2,
                default=0.33,
                max_digits=4,
                verbose_name="barcode bar width, mm",
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="barcode_height_mm",
            field=models.PositiveSmallIntegerField(
                default=16, verbose_name="barcode height, mm"
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="barcode_text_font_size",
            field=models.PositiveSmallIntegerField(
                default=7, verbose_name="barcode text font size"
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="internal_code_font_size",
            field=models.PositiveSmallIntegerField(
                default=6, verbose_name="internal code font size"
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="item_name_font_size",
            field=models.PositiveSmallIntegerField(
                default=8, verbose_name="item name font size"
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="margin_bottom_mm",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="margin bottom, mm"
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="margin_left_mm",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="margin left, mm"
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="margin_right_mm",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="margin right, mm"
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="margin_top_mm",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="margin top, mm"
            ),
        ),
    ]
