# Generated by Django 6.0.5 on 2026-05-24 16:07

import django.db.models.deletion
from django.db import migrations, models

def create_default_elements(apps, schema_editor):
    LabelTemplate = apps.get_model("core", "LabelTemplate")
    LabelTemplateElement = apps.get_model("core", "LabelTemplateElement")
    for template in LabelTemplate.objects.all():
        defaults = [
            ("item_name", 3, 3, 52, 8, template.item_name_font_size, template.show_item_name, 10),
            ("internal_code", 3, 12, 52, 5, template.internal_code_font_size, template.show_internal_code, 20),
            ("barcode", 6, 18, 46, template.barcode_height_mm, 8, True, 30),
            ("barcode_text", 6, 35, 46, 4, template.barcode_text_font_size, template.show_barcode_text, 40),
        ]
        for element_type, x, y, width, height, font_size, is_visible, sort_order in defaults:
            LabelTemplateElement.objects.create(
                template=template, element_type=element_type, x_mm=x, y_mm=y, width_mm=width, height_mm=height,
                font_size=font_size, is_visible=is_visible, sort_order=sort_order
            )

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_delete_legacy_usage_places"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelTemplateElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("item_name", "Назва товару"),
                            ("internal_code", "Внутрішній код"),
                            ("barcode", "Штрихкод"),
                            ("barcode_text", "Текст штрихкоду"),
                            ("custom_text", "Довільний текст"),
                        ],
                        max_length=32,
                        verbose_name="Тип елемента",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Назва елемента"
                    ),
                ),
                (
                    "text",
                    models.CharField(blank=True, max_length=255, verbose_name="Текст"),
                ),
                (
                    "x_mm",
                    models.DecimalField(
                        decimal_places=2, default=3, max_digits=6, verbose_name="X, мм"
                    ),
                ),
                (
                    "y_mm",
                    models.DecimalField(
                        decimal_places=2, default=3, max_digits=6, verbose_name="Y, мм"
                    ),
                ),
                (
                    "width_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=6,
                        verbose_name="Ширина, мм",
                    ),
                ),
                (
                    "height_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=4,
                        max_digits=6,
                        verbose_name="Висота, мм",
                    ),
                ),
                (
                    "font_size",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="Розмір шрифту"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Видимий"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="core.labeltemplate",
                        verbose_name="Шаблон етикетки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Елемент шаблону етикетки",
                "verbose_name_plural": "Елементи шаблону етикетки",
                "ordering": ["sort_order", "id"],
                "unique_together": {("template", "element_type", "sort_order")},
            },
        ),
        migrations.RunPython(create_default_elements, migrations.RunPython.noop),
    ]
