# Generated by Django 6.0.5 on 2026-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_labeltemplateelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeltemplateelement",
            name="text",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Текст"
            ),
        ),
        migrations.AlterField(
            model_name="labeltemplateelement",
            name="element_type",
            field=models.CharField(
                choices=[
                    ("item_name", "Назва товару"),
                    ("internal_code", "Внутрішній код"),
                    ("barcode", "Штрихкод"),
                    ("barcode_text", "Текст штрихкоду"),
                    ("custom_text", "Власний текст"),
                ],
                max_length=32,
                verbose_name="Тип елемента",
            ),
        ),
    ]
