# Generated by Django 6.0.5 on 2026-05-28 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_labeltemplateelement_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_stock_movements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Створив",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_stock_movements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Виконав",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_stock_movements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Оновив",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Дія")),
                (
                    "object_type",
                    models.CharField(max_length=100, verbose_name="Об'єкт"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID об'єкта"
                    ),
                ),
                ("object_repr", models.TextField(blank=True, verbose_name="Об'єкт")),
                (
                    "changes",
                    models.JSONField(blank=True, default=dict, verbose_name="Зміни"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адреса"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал аудиту",
                "verbose_name_plural": "Журнал аудиту",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
