# Generated by Django 6.0.5 on 2026-05-28 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_stockmovement_created_by_stockmovement_performed_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="cancellation_movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_original_movements",
                to="core.stockmovement",
                verbose_name="Рух анулювання",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="Причина анулювання"),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Час анулювання"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_stock_movements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Анулював",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="Анулювано"),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_movements",
                to="core.stockmovement",
                verbose_name="Рух анулювання",
            ),
        ),
    ]
