# Generated by Django 6.0.5 on 2026-05-28 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_existing_role_access(apps, schema_editor):
    UserWarehouseAccess = apps.get_model("core", "UserWarehouseAccess")
    Warehouse = apps.get_model("core", "Warehouse")
    Group = apps.get_model("auth", "Group")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    active_warehouses = list(Warehouse.objects.filter(is_active=True))
    if not active_warehouses:
        return

    admin_group = Group.objects.filter(name="Адміністратор складу").first()
    storekeeper_group = Group.objects.filter(name="Комірник").first()

    # Backward compatibility: users who could work across warehouses before
    # this migration keep that access. Superusers intentionally do not need
    # explicit rows because access checks treat them as unrestricted.
    if admin_group is not None:
        admins = User.objects.filter(
            groups=admin_group,
            is_superuser=False,
        ).distinct()
        for user in admins:
            for warehouse in active_warehouses:
                access, created = UserWarehouseAccess.objects.get_or_create(
                    user=user,
                    warehouse=warehouse,
                    defaults={"can_delegate": True, "is_active": True},
                )
                if not created and (
                    not access.is_active or not access.can_delegate
                ):
                    access.is_active = True
                    access.can_delegate = True
                    access.save(update_fields=["is_active", "can_delegate", "updated_at"])

    if storekeeper_group is not None:
        storekeepers = User.objects.filter(
            groups=storekeeper_group,
            is_superuser=False,
        ).distinct()
        for user in storekeepers:
            for warehouse in active_warehouses:
                UserWarehouseAccess.objects.get_or_create(
                    user=user,
                    warehouse=warehouse,
                    defaults={"can_delegate": False, "is_active": True},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_stock_movement_cancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWarehouseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_delegate', models.BooleanField(default=False, verbose_name='Може делегувати доступ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Доступ до складу',
                'verbose_name_plural': 'Доступ до складів',
                'ordering': ['user__username', 'warehouse__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'warehouse'), name='core_user_warehouse_access_unique_user_warehouse')],
            },
        ),
        migrations.RunPython(grant_existing_role_access, migrations.RunPython.noop),
    ]
