# Generated by Django 6.0.5 on 2026-06-15 05:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_stockbalance_qty_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва / товар')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Запитана кількість')),
                ('unit', models.CharField(max_length=64, verbose_name='Одиниця виміру')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Орієнтовна ціна за одиницю')),
                ('currency', models.CharField(default='UAH', max_length=8, verbose_name='Валюта')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Постачальник')),
                ('supplier_url', models.URLField(blank=True, verbose_name='Посилання постачальника')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата погодження')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата відхилення')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('pending_approval', 'Очікує погодження'), ('approved', 'Погоджено'), ('rejected', 'Відхилено'), ('ordered', 'Замовлено'), ('cancelled', 'Скасовано')], default='draft', max_length=24, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Погодив')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Відхилив')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявник')),
            ],
            options={
                'verbose_name': 'Заявка на закупівлю',
                'verbose_name_plural': 'Заявки на закупівлю',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_qty__gt', 0)), name='purchase_request_requested_qty_positive'), models.CheckConstraint(condition=models.Q(('estimated_unit_price__gte', 0)), name='purchase_request_estimated_price_non_negative')],
            },
        ),
    ]
