# Generated by Django 6.0.5 on 2026-06-15 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_purchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='receiving_base_status',
            field=models.CharField(blank=True, choices=[('approved', 'Погоджено'), ('ordered', 'Замовлено')], max_length=24),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_receive_movements', to='core.purchaserequest', verbose_name='Заявка на закупівлю'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending_approval', 'Очікує погодження'), ('approved', 'Погоджено'), ('rejected', 'Відхилено'), ('ordered', 'Замовлено'), ('partially_received', 'Частково отримано'), ('received', 'Отримано'), ('cancelled', 'Скасовано')], default='draft', max_length=24, verbose_name='Статус'),
        ),
    ]
