# Generated by Django 6.0.5 on 2026-06-15 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_match_purchase_requests_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='core.item', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_comment',
            field=models.TextField(blank=True, verbose_name='Коментар відхилення'),
        ),
    ]
