# Generated by Django 6.0.5 on 2026-06-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_purchaserequest_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('can_view_purchase_requests', 'Може переглядати заявки на закупівлю'), ('can_create_purchase_requests', 'Може створювати заявки на закупівлю'), ('can_approve_purchase_requests', 'Може погоджувати заявки на закупівлю'), ('can_update_purchase_request_tracking', 'Може змінювати оплату та доставку заявок')], 'verbose_name': 'Заявка на закупівлю', 'verbose_name_plural': 'Заявки на закупівлю'},
        ),
        migrations.AlterModelOptions(
            name='userwarehouseaccess',
            options={'ordering': ['user__username', 'warehouse__name'], 'permissions': [('can_access_warehouse', 'Може входити в складську систему')], 'verbose_name': 'Доступ до складу', 'verbose_name_plural': 'Доступ до складів'},
        ),
    ]
