# Generated by Django 6.0.5 on 2026-06-21 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_purchaserequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='Причина архівування'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архівування'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Архівував'),
        ),
    ]
