from django.urls import path

from . import views

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("units/", views.directory_view(views.DirectoryListView, "unit"), name="unit_list"),
    path("units/create/", views.directory_view(views.DirectoryCreateView, "unit"), name="unit_create"),
    path("units/<int:pk>/edit/", views.directory_view(views.DirectoryUpdateView, "unit"), name="unit_update"),
    path("units/<int:pk>/archive/", views.directory_view(views.DirectoryArchiveView, "unit"), name="unit_archive"),
    path("units/<int:pk>/restore/", views.directory_view(views.DirectoryRestoreView, "unit"), name="unit_restore"),
    path("categories/", views.directory_view(views.DirectoryListView, "category"), name="category_list"),
    path("categories/create/", views.directory_view(views.DirectoryCreateView, "category"), name="category_create"),
    path("categories/<int:pk>/edit/", views.directory_view(views.DirectoryUpdateView, "category"), name="category_update"),
    path("categories/<int:pk>/archive/", views.directory_view(views.DirectoryArchiveView, "category"), name="category_archive"),
    path("categories/<int:pk>/restore/", views.directory_view(views.DirectoryRestoreView, "category"), name="category_restore"),
    path("recipients/", views.directory_view(views.DirectoryListView, "recipient"), name="recipient_list"),
    path("recipients/create/", views.directory_view(views.DirectoryCreateView, "recipient"), name="recipient_create"),
    path("recipients/<int:pk>/edit/", views.directory_view(views.DirectoryUpdateView, "recipient"), name="recipient_update"),
    path("recipients/<int:pk>/archive/", views.directory_view(views.DirectoryArchiveView, "recipient"), name="recipient_archive"),
    path("recipients/<int:pk>/restore/", views.directory_view(views.DirectoryRestoreView, "recipient"), name="recipient_restore"),
    path("items/", views.directory_view(views.DirectoryListView, "item"), name="item_list"),
    path("items/create/", views.directory_view(views.DirectoryCreateView, "item"), name="item_create"),
    path("items/<int:pk>/edit/", views.directory_view(views.DirectoryUpdateView, "item"), name="item_update"),
    path("items/<int:pk>/archive/", views.directory_view(views.DirectoryArchiveView, "item"), name="item_archive"),
    path("items/<int:pk>/restore/", views.directory_view(views.DirectoryRestoreView, "item"), name="item_restore"),
    path("warehouses/", views.directory_view(views.DirectoryListView, "warehouse"), name="warehouse_list"),
    path("warehouses/create/", views.directory_view(views.DirectoryCreateView, "warehouse"), name="warehouse_create"),
    path("warehouses/<int:pk>/edit/", views.directory_view(views.DirectoryUpdateView, "warehouse"), name="warehouse_update"),
    path("warehouses/<int:pk>/archive/", views.directory_view(views.DirectoryArchiveView, "warehouse"), name="warehouse_archive"),
    path("warehouses/<int:pk>/restore/", views.directory_view(views.DirectoryRestoreView, "warehouse"), name="warehouse_restore"),
    path("locations/", views.directory_view(views.DirectoryListView, "location"), name="location_list"),
    path("locations/create/", views.directory_view(views.DirectoryCreateView, "location"), name="location_create"),
    path("locations/<int:pk>/edit/", views.directory_view(views.DirectoryUpdateView, "location"), name="location_update"),
    path("locations/<int:pk>/archive/", views.directory_view(views.DirectoryArchiveView, "location"), name="location_archive"),
    path("locations/<int:pk>/restore/", views.directory_view(views.DirectoryRestoreView, "location"), name="location_restore"),
    path("stock-balances/", views.StockBalanceListView.as_view(), name="stockbalance_list"),
]
